name: Run the MultiverseScanner

on:
  workflow_call:
    inputs:
      agentVersion:
        description: 'Agent version being tested'
        default: '0.0.0.0'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      agentVersion:
        description: 'Agent version being tested'
        default: '0.0.0.0'
        required: true

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true

jobs:

  build-run-publish-multiverse-testing:
    name: Build and Publish Multiverse Testing Suite
    runs-on: windows-2019

    env:
      multiverse_solution_path: ${{ github.workspace }}\tests\Agent\MultiverseTesting\MultiverseTesting.sln
      multiverse_artifacts_path: ${{ github.workspace }}\tests\Agent\MultiverseTesting\ConsoleScanner\bin\Release\netcoreapp3.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Multiverse Testing Suite
        id: multiverse-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.multiverse_artifacts_path }}
          key: multiverse-${{ hashFiles('**/tests/Agent/MultiverseTesting') }}

      - name: Add msbuild to PATH
        if: steps.multiverse-cache.outputs.cache-hit != 'true'
        uses: microsoft/setup-msbuild@v1

      - name: Build MultiverseTesting.sln
        if: steps.multiverse-cache.outputs.cache-hit != 'true'
        run: |
          Write-Host "List NuGet Sources"
          dotnet nuget list source # For unknown reasons, this step is necessary to avoid subsequent problems with NuGet package restore
          Write-Host "MSBuild.exe -restore -m -p:Configuration=Release -p:AllowUnsafeBlocks=true ${{ env.multiverse_solution_path }}"
          MSBuild.exe -restore -m -p:Configuration=Release -p:AllowUnsafeBlocks=true ${{ env.multiverse_solution_path }}
        shell: powershell

      - name: Setup .NET Core 3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Run ConsoleScanner
        run: |
          cd ${{ env.multiverse_artifacts_path }}
          .\ConsoleScanner.exe ".\config.yml" ".\reports.yml"
        shell: powershell

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: mvs-reports
          path: ${{ github.workspace }}\reports.yml
          if-no-files-found: error

      - name: Run ReportBuilder
        run: |
          cd ${{ env.multiverse_artifacts_path }}
          .\ReportBuilder.exe "${{ inputs.agentVersion }}" ".\reports.yml" ".\docs\mvs"
        shell: powershell

#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@4
#        with:
#          branch: gh-pages
#          folder: .
